# Generated by Django 2.1.5 on 2021-12-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuserholding',
            name='current_holdings',
            field=models.FloatField(default=1000000.0),
        ),
        migrations.AlterField(
            model_name='userholding',
            name='holdings',
            field=models.FloatField(default=1000000.0),
        ),
    ]
